README
Without indent, `make` reports errors in a directory called codelets.  
It also reports `/bin/bash: indent: command not found` not far away.
For my Ubuntu 14.04 flavor, a simple `sudo apt-get install indent` made `make` work as expected.
I hope this pull request does not enter in the world of obvious-spam-pull requests. I though it might be useful to non-specialists like me.
=> add indent to requirements

genfft/unique.ml
OCaml became smart enough to break this trick. It inlines `make_aux` starting from 4.02.0, and all generated tokens are the same.
```ocaml
(* this depends on the compiler not being too smart *)
let make () =
let make_aux x = Unique x in
make_aux ()
(* note that the obvious definition
let make () = Unique ()
fails *)
```
It seems this led to generation of wrong codelets (at least genfft built with OCaml 4.01.0 and 4.02.3 generated different codelets).
I've implemented "legal" unique token generation.
=> Fixed unique token generation in genfft

threads/threads.c
otherwise an i686-w64-mingw32 cross compile is giving
```
libtool: link: i686-w64-mingw32-gcc -march=pentium4 -m32  -std=gnu99 -shared  -Wl,--whole-archive kernel/.libs/libkernel.a dft/.libs/libdft.a dft/scalar/.libs/libdft_scalar.a dft/scalar/codelets/.libs/libdft_scalar_codelets.a rdft/.libs/librdft.a rdft/scalar/.libs/librdft_scalar.a rdft/scalar/r2cf/.libs/librdft_scalar_r2cf.a rdft/scalar/r2cb/.libs/librdft_scalar_r2cb.a rdft/scalar/r2r/.libs/librdft_scalar_r2r.a reodft/.libs/libreodft.a api/.libs/libapi.a simd-support/.libs/libsimd_support.a simd-support/.libs/libsimd_sse2_nonportable.a dft/simd/avx/.libs/libdft_avx_codelets.a rdft/simd/avx/.libs/librdft_avx_codelets.a threads/.libs/libfftw3f_threads.a -Wl,--no-whole-archive   -march=pentium4 -m32 -O3 -mtune=native -malign-double …
```
=> #include <intrin.h> in threads.c for windows build

simd-support/simd-vsx.h
defined(__POWER8_VECTOR__) && defined(__GNUC__) && defined(__LITTLE_ENDIAN__) is true for IBM XLC compiler for which we should use the intrinsic __vpermxor instead of __builtin_crypto_vpermxor.
=> Update simd-vsx.h to support building with IBM XLC

simd-support/simd-avx512.h
FFTW alignment is only 16 bytes. AVX512 requires 64 bytes.
Thus unaligned load/store is required. AVX256 does the same.
=> Fix AVX512 load+store

kernel/cycle.h
The Android headers defines `CLOCK_SGI_CYCLE` but the call fails at runtime as it's not implemented.
Combined with getticks() not checking the return value of clock_gettime() this currently causes bogus values to be returned from getticks() on an unpatched Android build.
=> Avoid trying to use CLOCK_SGI_CYCLE on Android

CMakeLists.txt, Makefile.am, cmake.config.h.in
Addresses #80: allow USERS to build fftw (not the developer side).
Supports static/shared, openmp, threads, various precision options, sse/avx.
Does not support fortran headers, mpi, other processor arches. Maybe that can added in the future. I think it's reasonably complete for now.
Tested here on linux, osx, msvc: https://github.com/xantares/fftw-cmake
cc @EikeVerdenhalven @junghans
=> Add user cmake support

kernel/cycle.h
Check for the correct pre-processor define HAVE_ARMV7A_CNTVCT from
config.h (instead of ARMV7A_HAS_CNTVCT) to fix the detection of the
cycle counter for ARMv7-A in the configure script (and actually use it
in the built library).
Without this fix, even the following ./configure call:
./configure --enable-neon --enable-single --enable-armv7a-cntvct \
--host=arm-linux-gnueabihf --disable-fortran \
CC="arm-linux-gnueabihf-gcc -march=armv7-a"
will emit the warning:
checking whether a cycle counter is available... no
***************************************************************
WARNING: No cycle counter found.  FFTW will use ESTIMATE mode
for all plans.  See the manual for more information.
***************************************************************
With this fix applied, ./configure will …
=> Fix ARMV7-A cycle counter detection

README-perfcnt.md, configure.ac, kernel/cycle.h
perf counters: add PMCCNTR for ARMv7 and add docs
The existing armv7 counter (CNTVCT) does need enabling from kernel mode (so
updated the configure help), and the enable bit is different from the PMU
enable bit (described in the new docs).
Tested on XU4: printed the returned counter values and they look reasonable.
If CNTVCT is not enabled in kernel mode, using the code in the new docs, I get illegal instruction at the instructions that reads CNTVCT.
FWIW, I PRed: https://github.com/thoughtpolice/enable_arm_pmu/pull/6
While at it also did this rename (easy to drop if can't break compatibility with the old --enable-armv8cc):
perf counters: name ARMv8 PMCCNTR_EL0 explicitly
For consistency with the rest.
RFC: It might be worth it to add the kernel module source into this repo, because those …
=> Pr  armv7 pmccntr counter and docs

doc/modern-fortran.texi
The use of quadruple-precision with Fortran does not require the inclusion of file `fftw3l.f03` (which contains the interfaces for extended precision), but it requires the inclusion of file `fftw3.f03`.
=> Fix typo in Fortran quadruple-precision doc.

genfft/util.ml
I noticed a mistake in the comment about what `Util.interval` produces.
`interval a b` produces the list `[a; a + 1; ...; b - 1]` rather than the stated `[a; 1; ...; b - 1]`.
Thanks!
=> Fix the incorrect comment about Util.interval

configure.ac
Closes #153 by passing the `-mavx512f` on clang if `--enable-avx512=yes`.
With this PR, it compiles for me (using Apple LLVM version 10.0.1).  However, my laptop does not support this instruction so I can't test it — would be good for someone to try it out before merging.
@matteo-frigo, I assume that this was not done initially just because clang did not support `-mavx512f` at the time AVX-512 support was merged?
=> enable avx512 on clang

README.md
[README.md](https://github.com/FFTW/fftw3/blob/master/README.md) refers the user to the text-only [README](https://github.com/FFTW/fftw3/blob/master/README), which contains - among other things, build instructions. Since the two files have a very similar name, this may lead to confusion for first-time users.
With this commit, a relative hyperlink pointing to `README` is added in `README.md`, in order to make it explicit what file is being referenced.
=> README.md: link to README

simd-support/x86-cpuid.h
`__cpuidex` is defined in `intrin.h`.
=> Fix x86 compilation in MSVC

api/fftw3.h, doc/legacy-fortran.texi, doc/threads.texi, doc/upgrading.texi, tests/fftw-bench.c, threads/api.c, threads/f77funcs.h
While you can currently set the maximum number of threads used by the planner,
there is no way to check that number. This simply adds a new function,
`planner_nthreads`, that provides this information, as was suggested by
@stevengj (JuliaMath/FFTW.jl#150).
I have no idea which files I should edit to introduce this new function beyond `threads/api.c`, due to my unfamiliarity with autoconf and the build system used by FFTW. I have additionally added `planner_nthreads` to `api/fftw3.h`, and `threads/f77funcs.h`. I was unsure how to test this new function, and I have not yet done so. I will try to figure that out soon, if someone with more experience does not do it before I can. 
I have also added `planner_nthreads` to all the relevant portions of the documentation that I could find.
=> First attempt at adding planner_nthreads

doc/reference.texi
Self-explanatory fix for typos in documentation.
=> Doc: remove duplicated "the"

CMakeLists.txt
Replace `CMAKE_SOURCE_DIR` by `CMAKE_CURRENT_SOURCE_DIR` in order to properly install fortran api if top `CMakeLists.txt` is wrapped in another one.
=> Fix fortran api installation when fftw CMakeLists is wrapped in another project

kernel/cycle.h
It seems that `CNTVCT_EL0` support is enabled by default on macOS running on the M1 (aarch64), but *not* `PMCCNTR_EL0`.     It makes sense to me to enable the former by default, as users are unlikely to know about this and not having a cycle counter really degrades FFTW's performance.
cc @matteo-frigo 
PS. Sorry for all of the whitespace changes; my editor is set to automatically delete trailing whitespace in `.c` files.
=> default to CNTVCT_EL0 cycle counter on Apple M1

CMakeLists.txt
This addresses a shortcoming observed with the Windows FFTW package on conda-forge, which uses CMake to build with MSVC. Those packages are built with SSE2 and AVX instructions enabled, and contrary to the desired behavior, users with processors that don't have AVX support have been reporting that the library fails to load. I finally tracked this down to the fact that when using CMake the *entire library* is built with the enabled SIMD flags, rather than just the specific SIMD files as with configure/make. Thus the compiler was inserting SIMD instructions elsewhere in the library, not gated by the check for whether the runtime CPU supported them.
This PR modifies the CMake build so that it applies the SIMD flags only on the appropriate source files as with configure/make. Patching this …
=> cmake: Set SIMD flags on appropriate source files only

api/api.h, api/apiplan.c, api/f77funcs.h, api/fftw3.h, doc/reference.texi, tests/fftw-bench.c
Closes #106.
Since plan execution is read-only, it seemed sufficient to implement this simply by adding an internal reference count to `fftw_plan`, so that `fftw_plan` just increments the counter and `fftw_destroy` plan decrements the counter, only de-allocating the plan when the reference count drops to zero.
@matteo-frigo, what do you think?
=> add fftw_copy_plan

configure.ac
Recent compilers (mostly clang) just abort on implicit function declaration. So this check could never succeed there, since the proper header for the tested function was not included.
=> Include missind header for Win32 Threads check

kernel/cycle.h
Cycle counter for RISC-V for both rv32 & rv64, using 'rdtime' (original commit is using 'rdcycle', but direct userland access is to be prohibited).
'rdtime' might have a low resolution on some hardware, unfortunately (same principle as the two counters on Aarch64).
Those changes are placed in the public domain by their author Romain Dolbeau.
This is an alternative to #348.
=> Riscv cyclecounter

Makefile.am, api/version.c, configure.ac, dft/codelet-dft.h, dft/conf.c, dft/simd/Makefile.am, dft/simd/lasx/Makefile.am, dft/simd/lsx/Makefile.am, kernel/cycle.h, kernel/ifftw.h, rdft/codelet-rdft.h, rdft/conf.c, rdft/simd/Makefile.am, rdft/simd/lasx/Makefile.am, rdft/simd/lsx/Makefile.am, simd-support/Makefile.am, simd-support/lasx.c, simd-support/lsx.c, simd-support/simd-common.h, simd-support/simd-lasx.h, simd-support/simd-lsx.h
These four patches have added SMID optimization for the loongarch（a new architecture of Loongson CPU）.
LSX is 128-bits and LASX is 256-bits.
previous PR (#363 ) will be closed.
=> Add SIMD optimization for LoongArch

mpi/api.c, mpi/f03api.sh, mpi/mpi-bench.c, rdft/vrank3-transpose.c, simd-support/simd-avx-128-fma.h, simd-support/simd-avx.h, simd-support/simd-avx2-128.h, simd-support/simd-avx2.h, simd-support/simd-common.h, simd-support/simd-maskedsve.h
Found via `codespell -q 3 -L aadd,aci,alo,fo,inout,intot,mone,nam,nd,ois,re-use,re-used,re-using,rin,shft,twon`
=> Fix various typos
